name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p artifacts/
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish with dotnet
      run: dotnet publish --self-contained -c Release -o artifacts/output -r "linux-x64"
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: artifacts/
